version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx-1.conf:/etc/nginx/nginx.conf:ro   # 초기엔 was1만
    depends_on:
      - was1

  was1:
    build:
      context: ./app
    container_name: was1
    ports:
      - "8081:8080"
    volumes:
      - ./app:/app
    command: >
      java -jar /app/app.jar
      --spring.config.location=file:/app/application.yml

  was2:
    build:
      context: ./app
    container_name: was2
    ports:
      - "8082:8080"
    volumes:
      - ./app:/app
    command: >
      java -jar /app/app.jar
      --spring.config.location=file:/app/application.yml
