server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3308/membership?rewriteBatchedStatements=true&useServerPrepStmts=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Hibernate SQL 로그 끔
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        order_inserts: true
        order_updates: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    p6spy: INFO
    org.mybatis: INFO
    org.apache.ibatis: INFO
    org.apache.ibatis.executor.BatchExecutor: DEBUG # 핵심! 실제 배치 수행 로그 확인용
    org.springframework.jdbc.core: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: WARN

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 로그 과다 시 주석 처리
