

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3308/membership?rewriteBatchedStatements=true&useServerPrepStmts=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      register-mbeans : true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Hibernate SQL 로그 끔
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        order_inserts: true
        order_updates: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO  # 전역 기본 로그 레벨을 에러로 제한

    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    # [1] 내가 작성한 서비스 코드 (log.info() 찍힌 로그)
    org.example.membership: INFO

    # [2] 기타 프레임워크 로그는 다 비활성화 (필요 시 DEBUG/INFO로 올릴 것)
    org.hibernate: OFF
    org.mybatis: OFF
    org.apache.ibatis: OFF
    org.springframework.transaction: OFF
    org.springframework.orm.jpa: OFF
    p6spy: OFF
    com.zaxxer.hikari: OFF

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 로그 과다 시 주석 처리

was:
  index: 0  # 이 값을 WAS별로 다르게 설정 (예: 0번, 1번, 2번...)

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs


