server:
  port: 8080
  tomcat:
    threads:
      max: 300
      min-spare: 20
    accept-count: 200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3308/membership?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      register-mbeans: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        order_inserts: true
        order_updates: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    root: WARN
    org.example.membership: DEBUG
    org.springframework.transaction: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com.zaxxer.hikari: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    url: /v3/api-docs
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
