spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3308/membership?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    job:
      enabled: false

logging:
  level:
    org.example: INFO
